import { createFileRoute, Link, useParams } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import { getCaseFn } from "@/lib/cases.functions";
import { ShieldAlert, Clock, ClipboardCheck, MessageSquare, Pill, Printer, Sparkles, AlertTriangle } from "lucide-react";

export const Route = createFileRoute("/_authenticated/app/case/$caseId")({
  component: CaseResults,
});

type RecRow = {
  recommendation_id: string;
  recommendation_type: string;
  title: string;
  product_name: string | null;
  brand: string | null;
  confidence: string;
  rank: number;
  why_triggered: string | null;
  pharmacist_checks: unknown;
  talking_points: unknown;
  safety_cautions: unknown;
  interaction_notes: unknown;
  matched_medicines: unknown;
  matched_patient_factors: unknown;
  source_references: unknown;
};

const TYPE_META: Record<string, { label: string; icon: typeof ShieldAlert; tone: string }> = {
  safety_caution: { label: "Safety caution", icon: ShieldAlert, tone: "signal" },
  administration: { label: "Administration & timing", icon: Clock, tone: "accent" },
  review_required: { label: "Review required", icon: ClipboardCheck, tone: "amber" },
  counselling_prompt: { label: "Counselling prompt", icon: MessageSquare, tone: "accent" },
  product_discussion: { label: "Product discussion", icon: Pill, tone: "muted" },
};

function asArr(v: unknown): string[] {
  return Array.isArray(v) ? (v as string[]) : [];
}

type SourceRef = { source: string; tier_label: string; note: string; url?: string };
function asRefs(v: unknown): SourceRef[] {
  return Array.isArray(v) ? (v as SourceRef[]) : [];
}

function CaseResults() {
  const { caseId } = useParams({ from: "/_authenticated/app/case/$caseId" });
  const fetchCase = useServerFn(getCaseFn);
  const { data, isLoading, error } = useQuery({
    queryKey: ["case", caseId],
    queryFn: () => fetchCase({ data: { caseId } }),
  });

  if (isLoading) return <div className="px-8 py-10 text-sm text-muted-foreground">Loading…</div>;
  if (error)
    return (
      <div className="px-8 py-10 text-sm text-signal">
        {error instanceof Error ? error.message : "Could not load case"}
      </div>
    );
  if (!data) return null;

  const { patientCase: p, recommendations: recs, senseCheck } = data as typeof data & {
    senseCheck: null | {
      status: string;
      model: string;
      applied_changes: unknown;
      rejected_changes: unknown;
      error_message: string | null;
      latency_ms: number | null;
      raw_response: { overall_note?: string } | null;
    };
  };
  const grouped = (Object.keys(TYPE_META) as Array<keyof typeof TYPE_META>).map((t) => ({
    type: t,
    items: (recs as RecRow[]).filter((r) => r.recommendation_type === t),
  }));

  return (
    <div className="px-8 py-10 max-w-5xl mx-auto">
      <div className="flex items-start justify-between no-print">
        <div>
          <Link to="/app/cases" className="text-xs uppercase tracking-[0.16em] text-muted-foreground hover:text-foreground">
            ← All reviews
          </Link>
          <h1 className="mt-2 text-3xl font-display font-medium">
            {p.case_label || `Patient · ${p.sex ?? "—"} · ${p.age ?? "?"}y`}
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            {recs.length} recommendation{recs.length === 1 ? "" : "s"} generated by deterministic rules.
          </p>
        </div>
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm hover:bg-secondary"
        >
          <Printer className="h-4 w-4" /> Print
        </button>
      </div>

      <div className="mt-6 pp-flat p-4 grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
        <Meta k="Pregnancy" v={p.pregnancy_status ?? "—"} />
        <Meta k="Breastfeeding" v={p.breastfeeding_status ?? "—"} />
        <Meta k="Allergies" v={p.allergies || "NKDA"} />
        <Meta k="History" v={p.medical_history || "—"} />
        <Meta k="Symptoms" v={p.symptoms || "—"} />
        <Meta k="Goal" v={p.counselling_goal || "—"} />
        <Meta
          k="Medications"
          v={
            Array.isArray(p.confirmed_medications)
              ? (p.confirmed_medications as Array<{ generic_name: string }>).map((m) => m.generic_name).join(", ") ||
                "—"
              : "—"
          }
        />
        <Meta k="Supplements" v={p.existing_supplements || "—"} />
      </div>

      {senseCheck && <SenseCheckBanner sc={senseCheck} />}

      {recs.length === 0 && (
        <div className="mt-8 pp-glass p-6">
          <p className="text-sm">
            No safety triggers fired for this combination. That doesn't mean there's nothing to do — apply your
            clinical judgement.
          </p>
        </div>
      )}

      <div className="mt-8 space-y-8">
        {grouped.map(
          (g) =>
            g.items.length > 0 && (
              <section key={g.type}>
                <h2 className="text-xs uppercase tracking-[0.18em] text-muted-foreground mb-3">
                  {TYPE_META[g.type].label}
                </h2>
                <div className="space-y-3">
                  {g.items.map((r) => (
                    <RecCard key={r.recommendation_id} r={r} />
                  ))}
                </div>
              </section>
            ),
        )}
      </div>
    </div>
  );
}

function RecCard({ r }: { r: RecRow }) {
  const meta = TYPE_META[r.recommendation_type] ?? TYPE_META.review_required;
  const Icon = meta.icon;
  const isSafety = r.recommendation_type === "safety_caution";

  return (
    <article className={`pp-glass p-5 ${isSafety ? "pp-safety" : ""}`}>
      <div className="flex items-start gap-3">
        <Icon className={`h-5 w-5 mt-0.5 ${isSafety ? "text-signal" : "text-accent"}`} />
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between gap-3">
            <h3 className="font-display text-lg leading-snug">{r.title}</h3>
            <span className="pp-chip text-[11px]">{r.confidence} confidence</span>
          </div>
          {r.why_triggered && <p className="mt-1.5 text-sm text-muted-foreground">{r.why_triggered}</p>}

          {asArr(r.talking_points).length > 0 && (
            <div className="mt-3">
              <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Talking points</p>
              <ul className="mt-1.5 text-sm space-y-1 list-disc list-inside marker:text-accent">
                {asArr(r.talking_points).map((t, i) => (
                  <li key={i}>{t}</li>
                ))}
              </ul>
            </div>
          )}

          {asArr(r.pharmacist_checks).length > 0 && (
            <div className="mt-3">
              <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Pharmacist checks</p>
              <ul className="mt-1.5 text-sm space-y-1 list-disc list-inside marker:text-foreground/40">
                {asArr(r.pharmacist_checks).map((t, i) => (
                  <li key={i}>{t}</li>
                ))}
              </ul>
            </div>
          )}

          {asArr(r.interaction_notes).length > 0 && (
            <div className="mt-3 text-sm">
              <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Interaction notes</p>
              <ul className="mt-1.5 space-y-1">
                {asArr(r.interaction_notes).map((t, i) => (
                  <li key={i}>{t}</li>
                ))}
              </ul>
            </div>
          )}

          <div className="mt-4 flex flex-wrap gap-2">
            {asArr(r.matched_medicines).map((m, i) => (
              <span key={i} className="pp-chip text-[11px]">
                {m}
              </span>
            ))}
            {asArr(r.matched_patient_factors).map((m, i) => (
              <span key={i} className="pp-chip text-[11px] bg-accent/10 border-accent/20">
                {m}
              </span>
            ))}
          </div>

          {asRefs(r.source_references).length > 0 && (
            <div className="mt-4 border-t border-hairline pt-3">
              <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Sources</p>
              <ul className="mt-1.5 text-xs space-y-1">
                {asRefs(r.source_references).map((s, i) => (
                  <li key={i} className="flex items-baseline gap-2">
                    <span className="pp-chip text-[10px] shrink-0">{s.tier_label}</span>
                    {s.url ? (
                      <a
                        href={s.url}
                        target="_blank"
                        rel="noreferrer"
                        className="text-foreground hover:underline underline-offset-2"
                      >
                        {s.source}
                        {s.note ? ` — ${s.note}` : ""}
                      </a>
                    ) : (
                      <span className="text-muted-foreground">
                        <span className="text-foreground">{s.source}</span>
                        {s.note ? ` — ${s.note}` : ""}
                      </span>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </article>
  );
}

function Meta({ k, v }: { k: string; v: string }) {
  return (
    <div>
      <p className="text-[10px] uppercase tracking-wider text-muted-foreground">{k}</p>
      <p className="text-sm">{v}</p>
    </div>
  );
}
