/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSetupRouteImport } from './routes/_authenticated/app.setup'
import { Route as AuthenticatedAppRulesRouteImport } from './routes/_authenticated/app.rules'
import { Route as AuthenticatedAppReviewRouteImport } from './routes/_authenticated/app.review'
import { Route as AuthenticatedAppReferencesRouteImport } from './routes/_authenticated/app.references'
import { Route as AuthenticatedAppQueueRouteImport } from './routes/_authenticated/app.queue'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app.products'
import { Route as AuthenticatedAppCasesRouteImport } from './routes/_authenticated/app.cases'
import { Route as AuthenticatedAppCaseCaseIdRouteImport } from './routes/_authenticated/app.case.$caseId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSetupRoute = AuthenticatedAppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRulesRoute = AuthenticatedAppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReviewRoute = AuthenticatedAppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReferencesRoute =
  AuthenticatedAppReferencesRouteImport.update({
    id: '/references',
    path: '/references',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQueueRoute = AuthenticatedAppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCasesRoute = AuthenticatedAppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCaseCaseIdRoute =
  AuthenticatedAppCaseCaseIdRouteImport.update({
    id: '/case/$caseId',
    path: '/case/$caseId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/cases': typeof AuthenticatedAppCasesRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/queue': typeof AuthenticatedAppQueueRoute
  '/app/references': typeof AuthenticatedAppReferencesRoute
  '/app/review': typeof AuthenticatedAppReviewRoute
  '/app/rules': typeof AuthenticatedAppRulesRoute
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/case/$caseId': typeof AuthenticatedAppCaseCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cases': typeof AuthenticatedAppCasesRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/queue': typeof AuthenticatedAppQueueRoute
  '/app/references': typeof AuthenticatedAppReferencesRoute
  '/app/review': typeof AuthenticatedAppReviewRoute
  '/app/rules': typeof AuthenticatedAppRulesRoute
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/case/$caseId': typeof AuthenticatedAppCaseCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/cases': typeof AuthenticatedAppCasesRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/queue': typeof AuthenticatedAppQueueRoute
  '/_authenticated/app/references': typeof AuthenticatedAppReferencesRoute
  '/_authenticated/app/review': typeof AuthenticatedAppReviewRoute
  '/_authenticated/app/rules': typeof AuthenticatedAppRulesRoute
  '/_authenticated/app/setup': typeof AuthenticatedAppSetupRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/case/$caseId': typeof AuthenticatedAppCaseCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/cases'
    | '/app/products'
    | '/app/queue'
    | '/app/references'
    | '/app/review'
    | '/app/rules'
    | '/app/setup'
    | '/app/'
    | '/app/case/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/cases'
    | '/app/products'
    | '/app/queue'
    | '/app/references'
    | '/app/review'
    | '/app/rules'
    | '/app/setup'
    | '/app'
    | '/app/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/cases'
    | '/_authenticated/app/products'
    | '/_authenticated/app/queue'
    | '/_authenticated/app/references'
    | '/_authenticated/app/review'
    | '/_authenticated/app/rules'
    | '/_authenticated/app/setup'
    | '/_authenticated/app/'
    | '/_authenticated/app/case/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/setup': {
      id: '/_authenticated/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AuthenticatedAppSetupRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rules': {
      id: '/_authenticated/app/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AuthenticatedAppRulesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/review': {
      id: '/_authenticated/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AuthenticatedAppReviewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/references': {
      id: '/_authenticated/app/references'
      path: '/references'
      fullPath: '/app/references'
      preLoaderRoute: typeof AuthenticatedAppReferencesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/queue': {
      id: '/_authenticated/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AuthenticatedAppQueueRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cases': {
      id: '/_authenticated/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AuthenticatedAppCasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/case/$caseId': {
      id: '/_authenticated/app/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/app/case/$caseId'
      preLoaderRoute: typeof AuthenticatedAppCaseCaseIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCasesRoute: typeof AuthenticatedAppCasesRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppQueueRoute: typeof AuthenticatedAppQueueRoute
  AuthenticatedAppReferencesRoute: typeof AuthenticatedAppReferencesRoute
  AuthenticatedAppReviewRoute: typeof AuthenticatedAppReviewRoute
  AuthenticatedAppRulesRoute: typeof AuthenticatedAppRulesRoute
  AuthenticatedAppSetupRoute: typeof AuthenticatedAppSetupRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCaseCaseIdRoute: typeof AuthenticatedAppCaseCaseIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCasesRoute: AuthenticatedAppCasesRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppQueueRoute: AuthenticatedAppQueueRoute,
  AuthenticatedAppReferencesRoute: AuthenticatedAppReferencesRoute,
  AuthenticatedAppReviewRoute: AuthenticatedAppReviewRoute,
  AuthenticatedAppRulesRoute: AuthenticatedAppRulesRoute,
  AuthenticatedAppSetupRoute: AuthenticatedAppSetupRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCaseCaseIdRoute: AuthenticatedAppCaseCaseIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
